// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SimpleStock.Web.Data;

#nullable disable

namespace SimpleStock.Web.Migrations;

[DbContext(typeof(StockContext))]
partial class StockContextModelSnapshot : ModelSnapshot
{
    protected override void BuildModel(ModelBuilder modelBuilder)
    {
#pragma warning disable 612, 618
        modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

        modelBuilder.Entity("SimpleStock.Models.StockMovement", b =>
            {
                b.Property<int>("Id")
                    .ValueGeneratedOnAdd()
                    .HasColumnType("INTEGER");

                b.Property<DateTime>("Date")
                    .HasColumnType("TEXT");

                b.Property<string>("Product")
                    .IsRequired()
                    .HasColumnType("TEXT");

                b.Property<int>("Quantity")
                    .HasColumnType("INTEGER");

                b.Property<string>("Recipient")
                    .HasColumnType("TEXT");

                b.Property<string>("Supplier")
                    .HasColumnType("TEXT");

                b.Property<int>("Type")
                    .HasColumnType("INTEGER");

                b.HasKey("Id");

                b.ToTable("StockMovements");
            });
#pragma warning restore 612, 618
    }
}
